### ISSUE TITLE
Poopr has no logo

### ISSUE THREAD

**Issue by KPLauritzen** [poopr/poopr#1]
We need a very very cool logo! Maybe something like:

💩r

or

p💩r (The eyes are 2 o's)

**Comment by felipepoulsen** [comment]
(y)

**Comment by 89AJ** [comment]
No you 🤡. Find something else.. 🙏

**Comment by KPLauritzen** [comment]
![image](https://user-images.githubusercontent.com/814491/27395586-8bc2fca6-56b0-11e7-92c7-b8d35f0032c1.png)

**Comment by 89AJ** [comment]
COOOOOL! 🤠
